#ifndef _FSM_H_
#define _FSM_H_

typedef enum{
    DISPLAY_TIME,
    DISPLAY_SEC,
    DISPLAY_DATE,
    DISPLAY_WDAY,
    DISPLAY_YEAR,
    DISPLAY_TEMP,
    DISPLAY_RH,
    DISPLAY_PRESS,
    DISPLAY_PHRASE,
    DISPLAY_ALARM,
    DISPLAY_USB,
    DISPLAY_ERROR,

    MENU_TIME,
    MENU_TIME_HOUR,
    MENU_TIME_MIN,
    MENU_TIME_SEC,
    
    MENU_DATE
    MENU_DATE_DAY,
    MENU_DATE_MOUNT,
    MENU_DATE_WDAY,
    MENU_DATE_YEAR,

    MENU_ALARM,
    MENU_ALARM_HOUR,
    MENU_ALARM_MIN,
    MENU_ALARM_STATE,

    MENU_FONT,
    MENU_FONT_FONT,
    MENU_FONT_REDACTOR,

    MENU_SENSOR,
    MENU_SENSOR_SENSOR,

    MENU_BR,
    MENU_BR_MIN,
    MENU_BR_MAX,
    MENU_BR_DAY_TIME,
    MENU_BR_NIGHT_TIME,

    MENU_PRESET,
    MENU_PRESET_PRESET,
    MENU_PRESET_TIME,

    MENU_PHRASE,
    MENU_PHRASE_CONFIG,
    MENU_PHRASE_CONFIG_TIME,
    MENU_PHRASE_CONFIG_TIME_MIN_START,
    MENU_PHRASE_CONFIG_TIME_HOUR_START,
    MENU_PHRASE_CONFIG_TIME_DATE_START,
    MENU_PHRASE_CONFIG_TIME_MIN_STOP,
    MENU_PHRASE_CONFIG_TIME_HOUR_STOP,
    MENU_PHRASE_CONFIG_TIME_DATE_STOP,
    MENU_PHRASE_CONFIG_PHRASE,
    MENU_PHRASE_REDACTOR,

    MENU_LANGUAGE,
    MENU_LANGUAGE_LANGUAGE,

    ERROR_STATE,
} fsm_state;

typedef enum{
    BUTTON_UP_CLICK,
    BUTTON_UP_HOLD,
    BUTTON_OK_CLICK,
    BUTTON_OK_HOLD,
    BUTTON_DOWN_CLICK,
    BUTTON_DOWN_HOLD,
} fsm_event;

#endif